export type WPUrlType = {
  title: string;
  url: string;
};

export const wpUrls: WPUrlType[] = [
  { title: 'Prediksi Togel Terpercaya di Wayantogel', url: 'wayantogel.store' },
  {
    title: 'Hasil Togel Macau Terupdate di KeltotoMacau',
    url: 'keltotomacau.store',
  },
  { title: 'Informasi Togel Terbaru di Sins88Info', url: 'sins88info.store' },
  { title: 'Prediksi Jitu Togel Persik4D Buzz', url: 'persik4dbuzz.store' },
  { title: 'Pasang Togel Online di Andara Online', url: 'andaraonline.store' },
  { title: 'Keluaran Togel Akurat di NadiemTogel', url: 'nadiemtogel.store' },
  { title: 'Angka Kramat SGP Terpercaya', url: 'angkakeramatsgponline.store' },
  { title: 'Togel Terpercaya di Vetogel Online', url: 'vetogelonline.store' },
  { title: 'Prediksi Togel Hari Ini di Lisboa77', url: 'lisboa77.store' },
  { title: 'Angka Sedarah Togel Online', url: 'angkasedarah.store' },
  { title: 'Togel Online Terpercaya di MPO700', url: 'mpo700.store' },
  { title: 'Pasang Togel Terbaik di Tobatogel', url: 'tobatogel.store' },
  { title: 'Togel Wayang88 Online Terpercaya', url: 'wayang88online.store' },
  { title: 'Slot Online Terbaik di BarbarSlot', url: 'barbarslotonline.store' },
  { title: 'Demo Slot PG Akun Gratis', url: 'akunslotdemopg.store' },
  { title: 'Info Dangdut4D Terbaru', url: 'dangdut4dinfo.store' },
  { title: 'Merdeka 189: Situs Togel Terbaik', url: 'merdeka189.store' },
  { title: 'Pasang Togel Online di Boke0', url: 'boke0.store' },
  { title: 'CuanSlot88: Slot Online Gacor', url: 'cuanslot88.store' },
  { title: 'Prediksi Togel Kebakaran Terbaru', url: 'notogelkebakaran.store' },
  { title: 'AromaToto: Togel Online Terbaik', url: 'aromatoto.store' },
  { title: 'Angka Shio Togel Terbaru', url: 'angkashiotogel.store' },
  { title: 'BataviaKDK: Keluaran Togel Terupdate', url: 'bataviakdkcom.store' },
  { title: 'JuniorTogel: Togel Terpercaya Online', url: 'juniortogel.store' },
  { title: 'Togel Rakyat: Keluaran Terbaru', url: 'togelrakyat.store' },
  { title: 'BGIBola2: Prediksi Bola Online', url: 'bgibola2.store' },
  { title: 'Keluaran Togel Terbaik di LogamToto', url: 'logamtoto.store' },
  { title: 'KebunToto: Situs Togel Terpercaya', url: 'kebuntoto.store' },
  { title: 'Prediksi Bola Online di BolaMacan', url: 'bolamacan.store' },
  { title: '8888Slot: Slot Online Terbaru', url: '8888slot.store' },
  { title: 'Oliv4D: Info Togel Online Terbaik', url: 'oliv4dinfo.store' },
  { title: 'Sandibet: Situs Togel Online', url: 'sandibetonline.store' },
  { title: 'Layanan Togel Terbaik di LimTogel', url: 'limtogel.store' },
  { title: 'Mega188: Situs Judi Slot Online', url: 'mega188.store' },
  { title: 'IDNHero: Togel Online Terpercaya', url: 'idnhero.store' },
  { title: 'AsusTogel: Keluaran Togel Terbaik', url: 'asustogel.store' },
  { title: 'CuanBet88: Situs Slot Gacor', url: 'cuanbet88online.store' },
  { title: 'AktorTogel: Prediksi Togel Terpercaya', url: 'aktortogel.store' },
  {
    title: 'Taysen Toto: Link Alternatif Terbaru',
    url: 'taysentotolinkalternatif.store',
  },
  { title: 'BossToto: Info Togel Online', url: 'bosstotoinfo.store' },
  { title: 'Catur777: Togel dan Slot Online', url: 'catur777.store' },
  { title: '3PrizeToto: Prediksi Togel Jitu', url: '3prizetoto.store' },
  { title: 'OkeWin: Situs Togel Online Terpercaya', url: 'okewin.store' },
  { title: 'Kamus88: Info Togel Terupdate', url: 'kamus88info.store' },
  { title: 'WDSukses: Togel Online Terbaik', url: 'wdsukses.store' },
  { title: 'LiveChatBola88: Prediksi Bola Jitu', url: 'livechatbola88.store' },
  { title: 'SapiMetal: Togel dan Slot Online', url: 'sapimetal.store' },
  {
    title: 'Istana Impian 3: Info Togel Terpercaya',
    url: 'istanaimpian3info.store',
  },
  { title: 'OVO88Bet: Situs Judi Slot Terbaik', url: 'ovo88betinfo.store' },
  { title: 'Prediksi Togel Terbaik di Bocah4D', url: 'bocah4d.store' },
  { title: 'Gohtogel: Keluaran Togel Terupdate', url: 'gohtogel.store' },
  { title: 'Dota88: Info Togel dan Slot Online', url: 'dota88info.store' },
  { title: 'Paito Warna Toto 4D Terpercaya', url: 'paitowarnatoto4d.store' },
  { title: 'IndoLottery: Info Togel Terbaik', url: 'indolotteryinfo.store' },
  { title: 'PapiTogel: Prediksi Togel Terupdate', url: 'papitogel.store' },
  { title: 'CrystalTogel: Togel Online Terbaik', url: 'crystaltogel.store' },
  { title: 'Mas4D Slot: Slot Online Gacor', url: 'mas4dslot.store' },
  { title: 'Hasil Togel Prancis Terbaru', url: 'hasilprancis.store' },
  { title: 'APG9: Info Togel Terpercaya', url: 'apg9info.store' },
  { title: 'PakBola88: Info Prediksi Bola', url: 'pakbola88info.store' },
  { title: 'AraiSlot: Info Slot Online Gacor', url: 'araislotinfo.store' },
  { title: 'Parlay88: Info Bola Parlay Terbaik', url: 'infoparlay88.store' },
  { title: 'GemoyToto: Togel Online Terpercaya', url: 'gemoytoto.store' },
  { title: 'Naga303: Info Prediksi Togel', url: 'naga303info.store' },
  { title: 'JayaBola: Info Bola Terbaru', url: 'jayabolainfo.store' },
  { title: 'Data HK 2004: Togel Terupdate', url: 'datahk2004.store' },
  { title: 'Parlay88: Info Bola Parlay Terbaru', url: 'parlay88info.store' },
  { title: 'KlikZeus: Situs Togel Online', url: 'klikzeus.store' },
  { title: 'PaitoNet: Prediksi Togel Terbaik', url: 'paitonet.store' },
  { title: 'Data SGP Warna: Togel Terbaru', url: 'datasgpwarna.store' },
  { title: 'Paito China Boss Paito Terbaik', url: 'paitochinabospaito.store' },
  { title: 'Wahana138: Info Togel Terupdate', url: 'wahana138info.store' },
  { title: 'MioToto: Togel Online Terpercaya', url: 'miototo.store' },
  { title: 'AsiaTogel88: Info Togel Terbaik', url: 'asiatogel88info.store' },
  { title: 'AGF vs Copenhagen: Prediksi Bola', url: 'agfvscopenhagen.store' },
  { title: 'Kanca4D: Info Togel Terpercaya', url: 'kanca4dinfo.store' },
  { title: 'IstanaToto: Info Togel Terupdate', url: 'istanatotoinfo.store' },
  { title: 'MesirToto: Info Togel Terbaik', url: 'mesirtotoinfo.store' },
  { title: 'Bandit4D: Togel Online Terpercaya', url: 'bandit4d.store' },
  { title: 'BeruangPlay: Slot Online Gacor', url: 'beruangplay.store' },
  { title: 'Sensa777: Info Slot Online Terbaru', url: 'sensa777info.store' },
  { title: 'CR777: Info Slot Online Terbaik', url: 'cr777slotinfo.store' },
  { title: 'ToinkToto: Prediksi Togel Jitu', url: 'toinktoto.store' },
  { title: 'Jap77: Info Togel Terupdate', url: 'jap77info.store' },
  { title: 'DuoLeDomino: Situs Slot Online', url: 'duoledomino.store' },
  { title: 'Fajar188: Info Togel Terpercaya', url: 'fajar188info.store' },
  { title: 'Coblos4D: Situs Togel Online Terbaik', url: 'coblos4d.store' },
  {
    title: 'Sepakbola Panama: Info Bola Terbaru',
    url: 'sepakbolapanama.store',
  },
  { title: 'Gacor7: Slot Online Gacor Terbaik', url: 'gacor7.store' },
  { title: 'Nova126: Info Judi Online Terpercaya', url: 'nova126online.store' },
  {
    title: 'CharlotteFC vs Inter Miami: Prediksi',
    url: 'charlottefcintermiami.store',
  },
  { title: 'Suhu303: Info Togel dan Slot Online', url: 'suhu303.store' },
  { title: 'Odin4D: Info Togel Online Terpercaya', url: 'odin4dinfo.store' },
  { title: 'AGB999: Situs Slot Online Terbaik', url: 'agb999.store' },
  { title: 'Cara Menang di Carawin77', url: 'carawin77info.store' },
  {
    title: 'Erek Erek Selingkuh: Prediksi Togel',
    url: 'erekerekselingkuh.store',
  },
  { title: 'Bola Siar: Nonton Bola Gratis', url: 'bolasiarnobartv.store' },
  { title: 'MPO4Slot: Info Slot Online Gacor', url: 'mpo4slotinfo.store' },
  { title: 'B88Sport: Situs Prediksi Bola Terpercaya', url: 'b88sport.store' },
  {
    title: 'Live Sydney 6D: Prediksi Togel Terbaik',
    url: 'livesydney6d.store',
  },
  { title: 'KokiToto: Situs Togel Terpercaya', url: 'kokitoto.store' },
  { title: 'Markas338: Info Togel dan Slot Online', url: 'markas338.store' },
  { title: 'SIPTogel: Prediksi Togel Terupdate', url: 'siptogel.store' },
  { title: 'Slot838: Info Slot Online Terbaik', url: 'slot838info.store' },
  { title: 'Putri77: Info Togel dan Slot Online', url: 'putri77info.store' },
  { title: 'AHMPasti: Situs Judi Online Terpercaya', url: 'ahmpasti.store' },
  {
    title: 'Klasemen Stade de Reims Terbaru',
    url: 'klasemenstadedereims.store',
  },
  {
    title: 'NowGoalBasketball: Skor Bola Basket Terupdate',
    url: 'nowgoalbasketball.store',
  },
  { title: 'SyairGucci: Prediksi Togel Terbaik', url: 'syairgucci.store' },
  { title: 'AuraJP: Situs Togel Online Terpercaya', url: 'aurajp.store' },
  {
    title: 'NanasToto 33831: Togel Online Terbaik',
    url: 'nanastoto33831.store',
  },
  {
    title: 'Result KingKong: Hasil Togel Terupdate',
    url: 'resultkingkong.store',
  },
  { title: 'R88Slot: Info Slot Online Terbaru', url: 'r88slotinfo.store' },
  { title: 'Live7MSport: Skor Bola Terbaru', url: 'live7msport.store' },
  { title: 'AlfaTogel: Prediksi Togel Jitu', url: 'alfatogel.store' },
  { title: 'Inter77: Info Judi Online Terbaik', url: 'inter77info.store' },
  { title: 'Cuan188: Info Togel dan Slot Online', url: 'cuan188info.store' },
  {
    title: 'VictoryToto: Situs Togel WAP Terbaik',
    url: 'victorytotowap.store',
  },
  { title: 'UUS777: Info Judi Online Terupdate', url: 'uus777info.store' },
  { title: 'Omega89: Info Slot Online Terbaik', url: 'omega89info.store' },
  { title: 'Buku Mimpi 19: Tafsir Mimpi dan Togel', url: 'bukumimpi19.store' },
  {
    title: 'No Punggung Mbappe: Info Jersey Bola',
    url: 'nopunggungmbappe.store',
  },
  { title: 'PutraLotre: Togel Online Terpercaya', url: 'putralotre.store' },
  { title: 'RatuSawer: Info Judi Slot Online', url: 'ratusawerinfo.store' },
  {
    title: 'TogelSlot88: Info Slot dan Togel Online',
    url: 'togelslot88.store',
  },
  { title: 'NewYorkMid: Prediksi Togel Jitu', url: 'newyorkmid.store' },
  { title: 'PustakaToto: Togel Online Terbaru', url: 'pustakatoto.store' },
  { title: 'JerukSlot: Info Slot Online Terbaik', url: 'jerukslot.store' },
  { title: 'FiaTogel88: Prediksi Togel Terpercaya', url: 'fiatogel88.store' },
  { title: 'GBO500: Situs Judi Online Terbaik', url: 'gbo500.store' },
  { title: 'PororoSlot: Info Slot Online Gacor', url: 'pororoslot.store' },
  { title: 'Neo777: Info Slot Online Terpercaya', url: 'neo777.store' },
  { title: 'Rekap4D: Hasil Togel Terbaru', url: 'rekap4d.store' },
  {
    title: 'Erek Erek Tentara: Tafsir Mimpi Togel',
    url: 'erekerektentara.store',
  },
  {
    title: 'FunGame77: Info Game Online Penghasil Uang',
    url: 'fungame77.store',
  },
  {
    title: 'SyairSGP Keraton: Prediksi Togel Terupdate',
    url: 'syairsgpkeraton.store',
  },
  {
    title: 'Paito Warna Kamboja: Hasil Togel Terbaru',
    url: 'paitowarnakamboja.store',
  },
  {
    title: 'TanganDewa Slot: Info Slot Online Gacor',
    url: 'tangandewaslot.store',
  },
  { title: 'IDCWin88: Situs Judi Online Terbaik', url: 'idcwin88.store' },
  { title: 'Kapsul88: Info Judi Online Terpercaya', url: 'kapsul88.store' },
  {
    title: 'Link Alternatif Dingdong Togel Terbaru',
    url: 'linkalternatifdingdongtogel.store',
  },
  { title: 'MPO212: Info Slot Online Terpercaya', url: 'mpo212info.store' },
  {
    title: 'Buku Mimpi 35: Tafsir dan Prediksi Togel',
    url: 'bukumimpi35.store',
  },
  {
    title: 'Rumus Ekor Jitu 99: Prediksi Togel Terbaik',
    url: 'rumusekorjitu99.store',
  },
  {
    title: 'AON338: Link Alternatif Judi Online',
    url: 'aon338linkalternatif.store',
  },
  { title: 'Sky338: Situs Judi Online Terpercaya', url: 'sky338.store' },
  {
    title: 'Kalender Togel Abadi: Prediksi Togel',
    url: 'kalendertogelabadi.store',
  },
  { title: 'Bingo89: Info Judi Online Terbaik', url: 'bingo89info.store' },
  {
    title: 'KratonBet: Info Judi Online Terpercaya',
    url: 'kratonbetinfo.store',
  },
  { title: 'RajaSpin: Info Slot Online Terbaru', url: 'rajaspininfo.store' },
  {
    title: 'Mimpi Digigit Monyet: Tafsir Mimpi Togel',
    url: 'mimpidigigitmonyet.store',
  },
  { title: 'Virgo4D: Prediksi Togel Terbaik', url: 'virgo4d.store' },
  { title: 'CahayaToto: Info Togel Terupdate', url: 'cahayatotoinfo.store' },
  { title: 'Prada188: Info Judi Online Terpercaya', url: 'prada188info.store' },
  { title: 'GandaToto: Situs Togel Terpercaya', url: 'gandatoto.store' },
  {
    title: 'BerkahWin88: Info Judi Online Gacor',
    url: 'berkahwin88info.store',
  },
  {
    title: 'CodaShop Chip Ungu: Info Top Up Game',
    url: 'codashopchipungu.store',
  },
  { title: 'NVM Adalah: Info Togel Online', url: 'nvmadalah.store' },
  { title: 'Halte4D Slot: Info Slot Online Terbaru', url: 'halte4dslot.store' },
  { title: 'Eze4D: Situs Togel Online Terpercaya', url: 'eze4d.store' },
  { title: 'NoTogel39: Prediksi Togel Terbaik', url: 'notogel39.store' },
  { title: 'Alfa77: Info Judi Online Terbaik', url: 'alfa77info.store' },
  {
    title: 'KangenWin Slot: Info Slot Online Gacor',
    url: 'kangenwinslot.store',
  },
  {
    title: 'Link Alternatif RajaTogel Terbaru',
    url: 'linkalternatifrajatogel.store',
  },
  {
    title: 'KlikWin88: Info Judi Online Terpercaya',
    url: 'klikwin88info.store',
  },
  {
    title: 'Erek Erek Pembunuh: Tafsir Mimpi Togel',
    url: 'erekerekpembunuh.store',
  },
  { title: 'ArenaToto: Situs Togel Online Terbaik', url: 'arenatoto.store' },
  { title: 'Zeus8M: Info Judi Slot Online Gacor', url: 'zeus8m.store' },
  { title: 'Lawan777: Info Slot Online Terpercaya', url: 'lawan777.store' },
  { title: 'PamanHoki: Info Judi Online Terbaik', url: 'pamanhoki.store' },
  {
    title: 'Link Alternatif AONCash: Situs Judi Online',
    url: 'linkalternatifaoncash.store',
  },
  { title: 'Prediksi99: Prediksi Togel Terupdate', url: 'prediksi99.store' },
  { title: 'Bakar777: Info Slot Online Terpercaya', url: 'bakar777info.store' },
  { title: 'LobyToto: Situs Togel Terbaik', url: 'lobytoto.store' },
  { title: 'Situs88: Info Judi Online Terupdate', url: 'situs88info.store' },
  {
    title: 'IndraTogel168: Togel Online Terpercaya',
    url: 'indratogel168.store',
  },
  {
    title: 'Purple Warna Apa: Tafsir Warna dan Togel',
    url: 'purplewarnaapa.store',
  },
  { title: 'BoyaPoker: Situs Poker Online Terbaik', url: 'boyapoker.store' },
  { title: 'KDK Batavia: Situs Togel Terpercaya', url: 'kdkbatavia.store' },
  { title: 'Kode 4D Slot: Info Slot Gacor Terbaru', url: 'kode4dslot.store' },
  { title: 'BSO888: Info Judi Slot Online', url: 'bso888.store' },
  { title: 'BravoMPO: Info Slot Online Terbaik', url: 'bravompoinfo.store' },
  { title: 'RajaVIP: Situs Judi Online Terpercaya', url: 'rajavip.store' },
  { title: 'GrabTogel: Situs Togel Online Terbaik', url: 'grabtogel.store' },
  {
    title: 'Erek Erek Penipu: Tafsir Mimpi dan Togel',
    url: 'erekerekpenipu.store',
  },
  { title: 'PaitoChelsea: Prediksi Togel Jitu', url: 'paitochelsea.store' },
  { title: 'ShioTogel: Prediksi dan Tafsir Mimpi', url: 'shiotogel.store' },
  { title: 'DataSGP: Hasil dan Prediksi Togel SGP', url: 'datasgpinfo.store' },
  { title: 'Gorila4D: Togel Online Terbaik', url: 'gorila4d.store' },
  { title: 'Sukses88: Situs Judi Online Terpercaya', url: 'sukses88.store' },
  { title: 'JuraganKoin: Info Judi Online Terbaru', url: 'juragankoin.store' },
  { title: 'Obat777: Info Judi Online Gacor', url: 'obat777info.store' },
  { title: 'Buku Mimpi: Tafsir Mimpi dan Togel', url: 'bukumimpiinfo.store' },
  {
    title: 'Game Domino Penghasil Saldo Dana Terbaik',
    url: 'gamedominopenghasilsaldodana.store',
  },
  { title: 'PWVIP4D: Info Togel Online Terpercaya', url: 'pwvip4dinfo.store' },
  { title: 'ZyngaTogel: Prediksi Togel Terbaru', url: 'zyngatogel.store' },
  {
    title: 'Pengeluaran 5D Macau: Hasil Togel Terupdate',
    url: 'pengeluaran5dmacau.store',
  },
  {
    title: 'TogelHOK: Info Togel Online Terpercaya',
    url: 'togelhokinfo.store',
  },
  { title: 'BessTogel: Situs Togel Online Terbaik', url: 'besstogel.store' },
  { title: 'TurboSpin: Info Slot Online Gacor', url: 'turbospin.store' },
  {
    title: 'SemarGroup Togel: Info Togel Terbaru',
    url: 'semargrouptogel.store',
  },
  { title: 'NTC22: Info Judi Online Terpercaya', url: 'ntc22info.store' },
  { title: 'DapurTogel: Prediksi Togel Terbaik', url: 'dapurtogel.store' },
  { title: 'Bucin4D: Info Togel Online Terbaru', url: 'bucin4dinfo.store' },
  {
    title: 'Erek Erek Kepiting: Tafsir Mimpi Togel',
    url: 'erekerekkepiting.store',
  },
  { title: 'Beli Chip Kuning: Info Top Up Game', url: 'belichipkuning.store' },
  { title: 'Artis777: Info Judi Online Gacor', url: 'artis777info.store' },
  { title: 'Mitra77: Info Judi Online Terpercaya', url: 'mitra77info.store' },
  { title: 'Mimpi Gempa: Tafsir Mimpi dan Togel', url: 'mimpigempa.store' },
  {
    title: 'NagaCuan: Info Togel Online Terpercaya',
    url: 'nagacuaninfo.store',
  },
  {
    title: 'Server Proxy WLA: Situs Proxy Togel Terbaik',
    url: 'serverproxywla.store',
  },
  { title: 'PastiWin: Info Judi Online Gacor', url: 'pastiwininfo.store' },
  { title: 'Raja258: Situs Judi Online Terbaik', url: 'raja258.store' },
  { title: 'Rokok2D Togel: Info Togel Terpercaya', url: 'rokok2dtogel.store' },
  { title: 'Japan168: Info Judi Online', url: 'japan168info.store' },
  { title: 'ToserBet: Info Judi Slot Online', url: 'toserbetinfo.store' },
  { title: 'Prediksi Bola: Prediksi Bola Jitu', url: 'prediksibola.store' },
  { title: 'PadangToto: Info Togel Padang', url: 'infopadangtoto.store' },
  {
    title: 'Game Slot Penghasil: Info Game Online Gacor',
    url: 'gameslotpenghasil.store',
  },
  { title: 'Juara Spin: Info Slot Online Terbaik', url: 'juaraspininfo.store' },
  { title: 'QQ Zeus: Info Judi Online Terpercaya', url: 'qqzeusinfo.store' },
  {
    title: 'Keluaran New York Mid: Hasil Togel Terupdate',
    url: 'keluarannewyorkmid.store',
  },
  { title: 'WinBet77: Situs Judi Online Terbaik', url: 'winbet77.store' },
  { title: 'Buku Mimpi 13: Tafsir Mimpi dan Togel', url: 'bukumimpi13.store' },
  { title: 'WieSlot: Info Slot Online Gacor', url: 'wieslotinfo.store' },
  { title: 'E Kings: Info Judi Online', url: 'ekingsinfo.store' },
  {
    title: 'MasterSlot88: Info Slot Online Terpercaya',
    url: 'masterslot88.store',
  },
  { title: 'BukuInfo: Info Togel dan Judi Online', url: 'bukuinfo.store' },
  { title: 'Domino Speeder: Info Game Domino', url: 'dominospeeder.store' },
  { title: 'Paito Midday: Prediksi Togel Jitu', url: 'paitomidday.store' },
  { title: 'Grup Keramat: Info Togel Online', url: 'grupkeramat.store' },
  { title: '1Bet2U: Situs Judi Online Terbaik', url: '1bet2u.store' },
  { title: 'Juara Utama: Info Judi Slot Online', url: 'juarautama.store' },
  { title: 'No Togel: Hasil Togel Terupdate', url: 'notogel.store' },
  {
    title: 'Erek Erek Kumbang: Tafsir Mimpi dan Togel',
    url: 'erekerekkumbang.store',
  },
  { title: 'Surga Lotre: Info Togel Terpercaya', url: 'surgalotreinfo.store' },
  { title: 'Link RajaToto: Info Togel Terupdate', url: 'linkrajatoto.store' },
  { title: 'Err Kerek: Tafsir Mimpi dan Togel', url: 'errkerek.store' },
  { title: 'Okto88: Situs Judi Slot Terbaik', url: 'okto88.store' },
  {
    title: 'SultanBet77: Situs Judi Online Terpercaya',
    url: 'sultanbet77.store',
  },
  { title: 'Link4D: Info Togel Online Terbaru', url: 'link4d.store' },
  { title: 'MimpiInfo: Tafsir Mimpi dan Togel', url: 'mimpiinfo.store' },
  {
    title: 'Ramayana Serang: Info Togel Terpercaya',
    url: 'ramayanaserang.store',
  },
  { title: 'GBO Play 138: Situs Judi Slot Terbaik', url: 'gboplay138.store' },
  {
    title: 'BandarColok Togel: Info Togel Terpercaya',
    url: 'bandarcoloktogel.store',
  },
  {
    title: 'Download APK Royal: Info Aplikasi Judi Online',
    url: 'downloadapkroyal.store',
  },
  { title: 'Sugi88: Info Judi Online Terbaru', url: 'sugi88info.store' },
  {
    title: 'Situs TOTO: Info Togel dan Judi Online',
    url: 'situstotocom.store',
  },
  { title: 'Paito Warna: Prediksi Togel Terbaik', url: 'paitowarnainfo.store' },
  { title: 'RTP JaminToto: Info Togel Terpercaya', url: 'rtpjamintoto.store' },
  {
    title: 'Sbobet Parlay: Prediksi Bola Terupdate',
    url: 'sbobetparlay.store',
  },
  { title: 'BP77 Home: Info Judi Slot Online', url: 'bp77home.store' },
  {
    title: 'Pemain Liga Championship: Info Sepak Bola',
    url: 'pemainligachampionship.store',
  },
  { title: 'Hongkong 6D: Info Togel Hongkong', url: 'hongkong6d.store' },
  { title: 'Erek Semut: Tafsir Mimpi dan Togel', url: 'ereksemut.store' },
  {
    title: 'Pantun Minta THR: Kumpulan Pantun Togel',
    url: 'pantunmintathr.store',
  },
  { title: 'Togelon88: Situs Togel Online Terpercaya', url: 'togelon88.store' },
  { title: 'TH7 Terkuat: Info Game Online', url: 'th7terkuat.store' },
  { title: 'CYK TOTO: Info Togel Online Terbaik', url: 'cyktoto.store' },
  { title: 'KLX4D: Situs Togel Online Terbaik', url: 'klx4d.store' },
  {
    title: 'Shio 2022 Togel: Prediksi dan Tafsir Mimpi',
    url: 'shio2022togel.store',
  },
  {
    title: 'Info Ambon 4D: Prediksi Togel Terupdate',
    url: 'infoambon4d.store',
  },
  { title: 'Gresik TOTO: Info Togel Online', url: 'gresiktoto.store' },
  { title: 'IDTOTO4D: Situs Togel Online Terpercaya', url: 'idtoto4d.store' },
  //duplicate delete later | just to fill the 50 array
  { title: 'Prediksi Togel Terpercaya di Wayantogel', url: 'wayantogel.store' },
  {
    title: 'Hasil Togel Macau Terupdate di KeltotoMacau',
    url: 'keltotomacau.store',
  },
  { title: 'Informasi Togel Terbaru di Sins88Info', url: 'sins88info.store' },
  { title: 'Prediksi Jitu Togel Persik4D Buzz', url: 'persik4dbuzz.store' },
  { title: 'Pasang Togel Online di Andara Online', url: 'andaraonline.store' },
  { title: 'Keluaran Togel Akurat di NadiemTogel', url: 'nadiemtogel.store' },
  { title: 'Angka Kramat SGP Terpercaya', url: 'angkakeramatsgponline.store' },
  { title: 'Togel Terpercaya di Vetogel Online', url: 'vetogelonline.store' },
  { title: 'Prediksi Togel Hari Ini di Lisboa77', url: 'lisboa77.store' },
  { title: 'Angka Sedarah Togel Online', url: 'angkasedarah.store' },
  { title: 'Togel Online Terpercaya di MPO700', url: 'mpo700.store' },
  { title: 'Pasang Togel Terbaik di Tobatogel', url: 'tobatogel.store' },
  { title: 'Togel Wayang88 Online Terpercaya', url: 'wayang88online.store' },
  { title: 'Slot Online Terbaik di BarbarSlot', url: 'barbarslotonline.store' },
  { title: 'Demo Slot PG Akun Gratis', url: 'akunslotdemopg.store' },
  { title: 'Info Dangdut4D Terbaru', url: 'dangdut4dinfo.store' },
  { title: 'Merdeka 189: Situs Togel Terbaik', url: 'merdeka189.store' },
  { title: 'Pasang Togel Online di Boke0', url: 'boke0.store' },
  { title: 'CuanSlot88: Slot Online Gacor', url: 'cuanslot88.store' },
  { title: 'Prediksi Togel Kebakaran Terbaru', url: 'notogelkebakaran.store' },
  { title: 'AromaToto: Togel Online Terbaik', url: 'aromatoto.store' },
  { title: 'Angka Shio Togel Terbaru', url: 'angkashiotogel.store' },
  { title: 'BataviaKDK: Keluaran Togel Terupdate', url: 'bataviakdkcom.store' },
  { title: 'JuniorTogel: Togel Terpercaya Online', url: 'juniortogel.store' },
  { title: 'Togel Rakyat: Keluaran Terbaru', url: 'togelrakyat.store' },
  { title: 'BGIBola2: Prediksi Bola Online', url: 'bgibola2.store' },
  { title: 'Keluaran Togel Terbaik di LogamToto', url: 'logamtoto.store' },
  { title: 'KebunToto: Situs Togel Terpercaya', url: 'kebuntoto.store' },
  { title: 'Prediksi Bola Online di BolaMacan', url: 'bolamacan.store' },
  { title: '8888Slot: Slot Online Terbaru', url: '8888slot.store' },
  { title: 'Oliv4D: Info Togel Online Terbaik', url: 'oliv4dinfo.store' },
  { title: 'Sandibet: Situs Togel Online', url: 'sandibetonline.store' },
  { title: 'Layanan Togel Terbaik di LimTogel', url: 'limtogel.store' },
  { title: 'Mega188: Situs Judi Slot Online', url: 'mega188.store' },
  { title: 'IDNHero: Togel Online Terpercaya', url: 'idnhero.store' },
  { title: 'AsusTogel: Keluaran Togel Terbaik', url: 'asustogel.store' },
];
